# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1857a2d7a1835b7cf569c5f4f456f9a0a75c6c84ed0b08a60d29abf57933040a5ecd06e8596c7789f4c495dff44190f1e671495fa5ed433c5f8ee927d774f1c7

test:
  secret_key_base: b985a1682c20de22e9256ddeec0488d6f3a4865b562a6e26e20c3c348ce698d60ef60c1a19b2ffd31237fb7fbd67b94b0b01b70354a934fe69a4084c0051340c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
